name: jarvis_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_calendar: ^4.3.0
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.1
  google_sign_in: ^5.4.0
  firebase_auth: ^5.1.0 
  firebase_core: ^3.6.0
  google_generative_ai: ^0.4.6
  sqflite: ^2.4.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  url_launcher: ^6.3.1
  android_intent_plus: ^5.2.0
  share_plus: ^10.1.2
  flutter_tts: ^3.2.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
